services:
  client:
    build: ../client
    ports:
      - "5173:5173"
    networks:
      - midsoa
    depends_on:
      - gateway
    environment:
      VITE_GATEWAY_API_URL: http://gateway:${GATEWAY_PORT}  

  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - midsoa
    restart: unless-stopped

  rabbitmq:
    networks:
      - midsoa
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
  
  gateway:
    build: ./gateway
    networks:
      - midsoa
    ports:
      - "3000:3000"
    env_file: .env
    depends_on: [users, tuitions, payments]
    environment:
      GATEWAY_PORT: ${GATEWAY_PORT}
      USERS_URL: http://users:${USERS_PORT}
      TUITIONS_URL: http://tuitions:${TUITIONS_PORT}
      PAYMENTS_URL: http://payments:${PAYMENTS_PORT}
    
  users:
    build: ./services/user
    networks:
      - midsoa
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on: [mysqldb]
    environment:
      PORT: ${PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SERVICE_TOKEN: ${SERVICE_TOKEN}
      MYSQL_DB_HOST: mysqldb
      MYSQL_DB_USER: ${MYSQL_DB_USER}
      MYSQL_DB_PASS: 123456
      MYSQL_DB_NAME: ${MYSQL_USERDB_NAME}
      MYSQL_DB_PORT: ${MYSQL_DB_PORT}

  tuitions:
    build: ./services/tuition
    networks:
      - midsoa
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on: [mysqldb, rabbitmq]
    environment:
      PORT: ${PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SERVICE_TOKEN: ${SERVICE_TOKEN}
      AMQP_URL_DOCKER: ${AMQP_URL_DOCKER}
      MYSQL_DB_HOST: mysqldb
      MYSQL_DB_USER: ${MYSQL_DB_USER}
      MYSQL_DB_PASS: 123456
      MYSQL_DB_NAME: ${MYSQL_TUITIONDB_NAME}
      MYSQL_DB_PORT: ${MYSQL_DB_PORT}

  payments:
    build: ./services/payment
    networks:
      - midsoa
    ports:
      - "3003:3003"
    env_file:
      - .env
    depends_on: [mysqldb, rabbitmq, users, tuitions]
    environment:
      PORT: ${PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SERVICE_TOKEN: ${SERVICE_TOKEN}
      AMQP_URL_DOCKER: ${AMQP_URL_DOCKER}
      MYSQL_DB_HOST: mysqldb
      MYSQL_DB_USER: ${MYSQL_DB_USER}
      MYSQL_DB_PASS: 123456
      MYSQL_DB_NAME: ${MYSQL_PAYMENTDB_NAME}
      MYSQL_DB_PORT: ${MYSQL_DB_PORT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_APP_PASSWORD: ${EMAIL_APP_PASSWORD}

networks:
  midsoa:
    driver: bridge
  
volumes:
  mysql_data: